name: Release
on:
  push:
    branches:
      - dev
      - main
      - next
      - alpha
      - beta
      - "*.x"
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          cache: yarn
          node-version: 18
          cache-dependency-path: yarn.lock

      - name: Install dependencies
        run: yarn install

      - name: Build Release
        run: yarn build

      - name: Build Storybook
        run: yarn build:storybook

      - name: Deploy GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: storybook-static
          target-folder: ${{ github.ref_name }}
          clean: true

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: yarn semantic-release
