name: Deploy Storybook
on:
  push:
    branches:
      - dev
permissions:
  contents: write
jobs:
  storybook:
    name: Deploy Storybook
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install and Build
        run: |
          npm ci
          npm run build:storybook

      - name: Deploy GitHub Pages
        uses: JamesIves/github-pages-deploy-action@3.6.2
        with:
          folder: storybook-static
